version: "3"
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - /home/farazz/farazaman-back:/app
    depends_on:
      - nextjs
  nextjs:
    build:
      context: /home/farazz/farazaman
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /home/farazz/farazaman:/app
